### Create a Movie with Authorization
PUT http://localhost:5149/api/movies/b17fda4a-8255-4561-b6ef-6a8638edc6f7
Accept: */*
Authorization: bearer xxx
Content-Type: application/json

{
  "title": "Gladiador",
  "yearOfRelease": 2000,
  "genres": [
    "War", "Blood"
  ]
}

# {
#   "title": "Titanic",
#   "yearOfRelease": 1997,
#   "genres": [
#     "Love", "Cheat"
#   ]
# }

